services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password_db
      - POSTGRES_DB=time_management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d time_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres-data:
