services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tmt-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password_db@postgres:5432/time_management?schema=public
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app

  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password_db
      - POSTGRES_DB=time_management
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d time_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres-data:
  node_modules:
